volumes:
    langgraph-data:
        driver: local
    qdrant-storage:
        driver: local

services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_DB}
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: the_data_guy_chat
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        volumes:
          - ./db:/data
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            VECTOR_STORAGE_PATH: /data/vector_store_tdg_5
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            LANGSMITH_PROJECT: the_data_guy_chat
            LANGCHAIN_TRACING_V2: true
            POSTGRES_URI: ${POSTGRES_URI}
    qdrant:
        image: qdrant/qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant-storage:/qdrant/storage